"""initial schema

Revision ID: d755b1cfc868
Revises: 
Create Date: 2026-08-01 07:33:24.605347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd755b1cfc868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=3), nullable=False),
    sa.Column('theme', sa.Enum('light', 'dark', name='theme_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_profile_id'), ['profile_id'], unique=True)

    op.create_table('habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('active_days', sa.String(length=20), server_default='0,1,2,3,4,5,6', nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_id'), ['id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_hash', name='uq_push_subscriptions_endpoint_hash')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index('ix_push_subscriptions_user_enabled', ['user_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('reading_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('quero_ler', 'lendo', 'concluido')", name='ck_reading_books_status'),
    sa.CheckConstraint('current_page <= total_pages', name='ck_reading_books_page_within_total'),
    sa.CheckConstraint('current_page >= 0', name='ck_reading_books_current_page_nonnegative'),
    sa.CheckConstraint('total_pages > 0', name='ck_reading_books_total_pages_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_books_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_books_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_books_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_books_user_id'), ['user_id'], unique=False)

    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=24), server_default='other', nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('repeat_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('next_list_id', sa.Integer(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('budget_cents IS NULL OR budget_cents >= 0', name='ck_shopping_lists_budget_nonnegative'),
    sa.CheckConstraint('revision >= 0', name='ck_shopping_lists_revision_nonnegative'),
    sa.CheckConstraint('total_cents >= 0', name='ck_shopping_lists_total_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_lists_completed_on'), ['completed_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_lists_planned_date'), ['planned_date'], unique=False)
        batch_op.create_index('ix_shopping_lists_user_completed', ['user_id', 'completed_on'], unique=False)
        batch_op.create_index('ix_shopping_lists_user_planned', ['user_id', 'planned_date'], unique=False)

    op.create_table('shopping_monthly_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('budget_cents >= 0', name='ck_shopping_monthly_budgets_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_monthly_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_monthly_budgets_id'), ['id'], unique=False)
        batch_op.create_index('uq_shopping_monthly_budgets_user_month', ['user_id', 'month'], unique=True)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=12), server_default='none', nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('recurrence_parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.CheckConstraint("recurrence IN ('none', 'daily', 'weekly', 'monthly')", name='ck_tasks_recurrence'),
    sa.CheckConstraint('recurrence_interval >= 1 AND recurrence_interval <= 365', name='ck_tasks_recurrence_interval'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index('ix_tasks_recurrence_parent', ['recurrence_parent_id'], unique=False)

    op.create_table('workout_exercise_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_key', sa.String(length=140), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), server_default='60', nullable=False),
    sa.Column('increment_kg', sa.Numeric(precision=5, scale=2), server_default='1.00', nullable=False),
    sa.CheckConstraint('increment_kg >= 0.25 AND increment_kg <= 20', name='ck_workout_exercise_preferences_increment_range'),
    sa.CheckConstraint('rest_seconds >= 15 AND rest_seconds <= 600', name='ck_workout_exercise_preferences_rest_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_key', name='uq_workout_exercise_preferences_user_key')
    )
    with op.batch_alter_table('workout_exercise_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercise_preferences_id'), ['id'], unique=False)
        batch_op.create_index('ix_workout_exercise_preferences_user', ['user_id'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_id'), ['id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sets', sa.String(length=20), nullable=True),
    sa.Column('reps', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_workout_id'), ['workout_id'], unique=False)

    op.create_table('habit_check_ins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uq_habit_check_ins_habit_date')
    )
    with op.batch_alter_table('habit_check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_check_ins_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_check_ins_id'), ['id'], unique=False)

    op.create_table('push_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('reminder_key', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'reminder_key', name='uq_push_deliveries_subscription_reminder')
    )
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_push_deliveries_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_deliveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_deliveries_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('reading_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('page >= 0', name='ck_reading_notes_page_nonnegative'),
    sa.ForeignKeyConstraint(['book_id'], ['reading_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_notes_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_notes_note_date'), ['note_date'], unique=False)

    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'focus')", name='ck_reading_sessions_source'),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_reading_sessions_duration'),
    sa.CheckConstraint('end_page >= start_page', name='ck_reading_sessions_page_order'),
    sa.CheckConstraint('start_page >= 0', name='ck_reading_sessions_start_page_nonnegative'),
    sa.ForeignKeyConstraint(['book_id'], ['reading_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_sessions_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_session_date'), ['session_date'], unique=False)

    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(checked_at IS NULL AND price_cents IS NULL) OR (checked_at IS NOT NULL AND price_cents IS NOT NULL)', name='ck_shopping_items_check_price_pair'),
    sa.CheckConstraint('price_cents IS NULL OR price_cents >= 0', name='ck_shopping_items_price_nonnegative'),
    sa.CheckConstraint('quantity >= 1', name='ck_shopping_items_quantity_positive'),
    sa.CheckConstraint('unit_price_cents IS NULL OR unit_price_cents >= 0', name='ck_shopping_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_items_shopping_list_id'), ['shopping_list_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('workout_title', sa.String(length=200), nullable=False),
    sa.Column('workout_day', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed')", name='ck_workout_sessions_status'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_workout_sessions_duration_nonnegative'),
    sa.CheckConstraint('rest_seconds >= 15 AND rest_seconds <= 600', name='ck_workout_sessions_rest_range'),
    sa.CheckConstraint('revision >= 0', name='ck_workout_sessions_revision_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_workout_sessions_user_status_started', ['user_id', 'status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_session_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('target_sets >= 1 AND target_sets <= 20', name='ck_workout_session_exercises_target_sets'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sort_order', name='uq_workout_session_exercises_order')
    )
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_session_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_session_exercises_session_id'), ['session_id'], unique=False)

    op.create_table('workout_set_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(completed_at IS NULL AND weight_kg IS NULL AND reps_completed IS NULL) OR (completed_at IS NOT NULL AND weight_kg IS NOT NULL)', name='ck_workout_set_logs_completion'),
    sa.CheckConstraint('reps_completed IS NULL OR (reps_completed >= 1 AND reps_completed <= 1000)', name='ck_workout_set_logs_reps'),
    sa.CheckConstraint('set_number >= 1 AND set_number <= 20', name='ck_workout_set_logs_number'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg >= 0 AND weight_kg <= 500)', name='ck_workout_set_logs_weight'),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['workout_session_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_exercise_id', 'set_number', name='uq_workout_set_logs_exercise_number')
    )
    with op.batch_alter_table('workout_set_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_set_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_set_logs_session_exercise_id'), ['session_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_set_logs_session_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_workout_set_logs_id'))

    op.drop_table('workout_set_logs')
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_session_exercises_session_id'))
        batch_op.drop_index(batch_op.f('ix_workout_session_exercises_id'))
        batch_op.drop_index(batch_op.f('ix_workout_session_exercises_exercise_id'))

    op.drop_table('workout_session_exercises')
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_workout_id'))
        batch_op.drop_index('ix_workout_sessions_user_status_started')
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_completed_at'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_items_shopping_list_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_items_id'))

    op.drop_table('shopping_items')
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_book_id'))

    op.drop_table('reading_sessions')
    with op.batch_alter_table('reading_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_notes_note_date'))
        batch_op.drop_index(batch_op.f('ix_reading_notes_id'))
        batch_op.drop_index(batch_op.f('ix_reading_notes_book_id'))

    op.drop_table('reading_notes')
    with op.batch_alter_table('push_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_push_deliveries_id'))
        batch_op.drop_index('ix_push_deliveries_created')

    op.drop_table('push_deliveries')
    with op.batch_alter_table('habit_check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_check_ins_id'))
        batch_op.drop_index(batch_op.f('ix_habit_check_ins_date'))

    op.drop_table('habit_check_ins')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_workout_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_id'))

    op.drop_table('workouts')
    with op.batch_alter_table('workout_exercise_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_exercise_preferences_user')
        batch_op.drop_index(batch_op.f('ix_workout_exercise_preferences_id'))

    op.drop_table('workout_exercise_preferences')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_recurrence_parent')
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('shopping_monthly_budgets', schema=None) as batch_op:
        batch_op.drop_index('uq_shopping_monthly_budgets_user_month')
        batch_op.drop_index(batch_op.f('ix_shopping_monthly_budgets_id'))

    op.drop_table('shopping_monthly_budgets')
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index('ix_shopping_lists_user_planned')
        batch_op.drop_index('ix_shopping_lists_user_completed')
        batch_op.drop_index(batch_op.f('ix_shopping_lists_planned_date'))
        batch_op.drop_index(batch_op.f('ix_shopping_lists_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_lists_completed_on'))
        batch_op.drop_index(batch_op.f('ix_shopping_lists_completed_at'))

    op.drop_table('shopping_lists')
    with op.batch_alter_table('reading_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_books_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_books_status'))
        batch_op.drop_index(batch_op.f('ix_reading_books_is_active'))
        batch_op.drop_index(batch_op.f('ix_reading_books_id'))

    op.drop_table('reading_books')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))
        batch_op.drop_index('ix_push_subscriptions_user_enabled')
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_id'))

    op.drop_table('habits')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_profile_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
